x-kafka-ci-environment: &kafka-ci-environment
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker-1:29093,2@broker-2:29093
  KAFKA_DEFAULT_REPLICATION_FACTOR: 2
  KAFKA_MIN_INSYNC_REPLICAS: 1
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 2
  KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1

services:
  broker-1:
    environment:
      <<: *kafka-ci-environment

  broker-2:
    environment:
      <<: *kafka-ci-environment

  init:
    environment:
      REPLICATION_FACTOR: 2
